site_name: Driving Log Replayer Documentation
site_url: https://tier4.github.io/driving_log_replayer
edit_uri: edit/main/docs/
repo_url: https://github.com/tier4/driving_log_replayer

docs_dir: docs
copyright: Copyright &copy; 2022 TIER IV Inc.

theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  font:
    text: Roboto
    code: Roboto Mono
  version:
    provider: mike

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
    - javascripts/config.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

plugins:
  - awesome-pages:
      strict: false
  - search
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        ja:
          name: 日本語
          build: true

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - mdx_truly_sane_lists:
      nested_indent: 2
  - pymdownx.highlight
  - pymdownx.superfences:
  - toc:
      permalink: "#"
      toc_depth: 3
