/clock:
  depth: 10
  durability: volatile
  history: keep_last
  reliability: best_effort
/perception/obstacle_segmentation/pointcloud:
  depth: 10
  durability: volatile
  history: keep_last
  reliability: best_effort
/diagnostics:
  depth: 1000
  durability: volatile
  history: keep_last
  reliability: best_effort
