[default]
data_directory = "$HOME/driving_log_replayer_data/default"
output_directory = "$HOME/driving_log_replayer_output/default"
autoware_path = "$HOME/autoware"

[localization]
data_directory = "$HOME/driving_log_replayer_data/localization"
output_directory = "$HOME/driving_log_replayer_output/localization"
autoware_path = "$HOME/autoware"

[yabloc]
data_directory = "$HOME/driving_log_replayer_data/yabloc"
output_directory = "$HOME/driving_log_replayer_output/yabloc"
autoware_path = "$HOME/autoware"

[eagleye]
data_directory = "$HOME/driving_log_replayer_data/eagleye"
output_directory = "$HOME/driving_log_replayer_output/eagleye"
autoware_path = "$HOME/autoware"

[ar_tag_based_localizer]
data_directory = "$HOME/driving_log_replayer_data/ar_tag_based_localizer"
output_directory = "$HOME/driving_log_replayer_output/ar_tag_based_localizer"
autoware_path = "$HOME/autoware"

[obstacle_segmentation]
data_directory = "$HOME/driving_log_replayer_data/obstacle_segmentation"
output_directory = "$HOME/driving_log_replayer_output/obstacle_segmentation"
autoware_path = "$HOME/autoware"

[perception]
data_directory = "$HOME/driving_log_replayer_data/perception"
output_directory = "$HOME/driving_log_replayer_output/perception"
autoware_path = "$HOME/autoware"

[annotationless_perception]
data_directory = "$HOME/driving_log_replayer_data/annotationless_perception"
output_directory = "$HOME/driving_log_replayer_output/annotationless_perception"
autoware_path = "$HOME/autoware"

[planning_control]
data_directory = "$HOME/driving_log_replayer_data/planning_control"
output_directory = "$HOME/driving_log_replayer_output/planning_control"
autoware_path = "$HOME/autoware"
