name: build-document

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  asciidoctor_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build html using asciidoctor
        id: documents
        uses: Analog-inc/asciidoctor-action@master
        with:
          shellcommand: asciidoctor ./docs/main.adoc -o ./docs/index.html -r asciidoctor-diagram -a allow-uri-read -a data-uri -a toc=left

      - name: Deploy html
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
